import { useMemo, useState } from "react";
import { ArrowLeft, ChevronDown, ChevronUp, Cpu, Filter, Home, Menu, Radio, Search, ShieldCheck, SlidersHorizontal, X, Zap } from "lucide-react";
import "./_group.css";
import "./NouraSmartStore.css";

type Category = "الكل" | "الشاشات" | "المفاتيح" | "الحساسات" | "الملحقات";
type Product = { id:number; name:string; category:Exclude<Category,"الكل">; tag:string; image:string; kind:"screen"|"switch"|"sensor"|"accessory"; specs:string[]; note:string; accent:"teal"|"coral"|"gold"|"slate"; colors?:{name:string; hex:string}[] };

const products:Product[] = [
  { id:1, name:"شاشة تحكم مركزية 5 بوصة", category:"الشاشات", tag:"تحكم مركزي", kind:"screen", image:"/__mockup/images/noura-smart-new-screen-5.jpg", specs:["شاشة لمس","بوابة Zigbee مدمجة","تعمل مع Tuya و Smart Life","تحكم كامل بالمنزل"], note:"شاشة صغيرة تجمع أجهزة البيت في مكان واحد.", accent:"teal" },
  { id:2, name:"شاشة تحكم مركزية 12.3 بوصة", category:"الشاشات", tag:"شاشة رئيسية", kind:"screen", image:"/__mockup/images/noura-smart-new-screen-123.jpg", specs:["شاشة لمس واسعة","تصميم جداري","واجهة منزلية ذكية","عرض الوقت والمشاهد"], note:"شاشة رئيسية كبيرة للمداخل والمساحات التي تحتاج حضوراً واضحاً.", accent:"gold" },
  { id:3, name:"شاشة تحكم مركزية 10 بوصة", category:"الشاشات", tag:"تجربة موسعة", kind:"screen", image:"/__mockup/images/noura-smart-new-screen-10.jpg", specs:["شاشة لمس كبيرة","مكبر صوت مدمج","تحكم بالمشاهد","واجهة منزلية ذكية"], note:"مركز تحكم واضح للبيوت التي تحتاج مساحة أكبر.", accent:"slate" },
  { id:4, name:"شاشة تحكم مركزية 8 بوصة", category:"الشاشات", tag:"تجربة متعددة", kind:"screen", image:"/__mockup/images/noura-smart-new-screen-8.jpg", specs:["لمس وأزرار وصوت","بوابة Bluetooth و Zigbee","تحكم عبر التطبيق","مشاهد مخصصة"], note:"تحكم مرن يناسب كل غرفة وكل طريقة استخدام.", accent:"teal" },
  { id:5, name:"شاشة تحكم مركزية 6 بوصة", category:"الشاشات", tag:"حجم مدمج", kind:"screen", image:"/__mockup/images/noura-smart-new-screen-6.jpg", specs:["شاشة لمس","ثلاثة أزرار جانبية","عرض الحرارة والوقت","تحكم بالمشاهد"], note:"حجم عملي للممرات وغرف النوم والمساحات الهادئة.", accent:"coral" },
  { id:6, name:"ريموت كنترول زقبي", category:"الملحقات", tag:"تحكم لاسلكي", kind:"accessory", image:"/__mockup/images/noura-smart-new-remote.jpg", specs:["أربعة أزرار","تحكم بالمشاهد","اتصال Zigbee","تصميم أسود"], note:"ريموت بسيط للمشاهد والإضاءة من أي مكان في الغرفة.", accent:"slate" },
  { id:7, name:"سويتش لمس ذكي — 4 أزرار", category:"المفاتيح", tag:"زجاج أسود", kind:"switch", image:"/__mockup/images/noura-smart-dme214.png", specs:["Zigbee 3.0","زجاج مقعر","إطار معدني أسود","L+N Wire · EU Standard"], note:"أربع وظائف ذكية في لوحة واحدة بتصميم هادئ.", accent:"slate", colors:[{name:"أسود",hex:"#202020"},{name:"ذهبي",hex:"#b48743"},{name:"أبيض",hex:"#f4f1ec"},{name:"رمادي",hex:"#8d8d8d"}] },
  { id:8, name:"سويتش لمس ذكي — 3 أزرار", category:"المفاتيح", tag:"زجاج أسود", kind:"switch", image:"/__mockup/images/noura-smart-dme213.png", specs:["Zigbee 3.0","زجاج مقعر","إطار معدني أسود","Tuya و Smart Life"], note:"ثلاثة مشاهد جاهزة ليومك بلمسة واحدة.", accent:"teal", colors:[{name:"أسود",hex:"#202020"},{name:"ذهبي",hex:"#b48743"},{name:"أبيض",hex:"#f4f1ec"},{name:"رمادي",hex:"#8d8d8d"}] },
  { id:9, name:"سويتش لمس ذكي — زرين", category:"المفاتيح", tag:"تحكم مزدوج", kind:"switch", image:"/__mockup/images/noura-smart-dme213.png", specs:["Zigbee 3.0","زرّان مستقلان","تصميم زجاجي","Tuya و Smart Life"], note:"تحكم مزدوج في لوحة واحدة، متوفر بالألوان التي تناسب جدارك.", accent:"gold", colors:[{name:"أسود",hex:"#202020"},{name:"ذهبي",hex:"#b48743"},{name:"أبيض",hex:"#f4f1ec"},{name:"رمادي",hex:"#8d8d8d"}] },
  { id:10, name:"سويتش لمس ذكي — زر واحد", category:"المفاتيح", tag:"تحكم بسيط", kind:"switch", image:"/__mockup/images/noura-smart-dme213.png", specs:["Zigbee 3.0","زر واحد مستقل","إطار ناعم","Tuya و Smart Life"], note:"حل هادئ ومباشر للممرات وغرف النوم، بأكثر من لون.", accent:"slate", colors:[{name:"أسود",hex:"#202020"},{name:"ذهبي",hex:"#b48743"},{name:"أبيض",hex:"#f4f1ec"},{name:"رمادي",hex:"#8d8d8d"}] },
  { id:11, name:"سويتش دايمر ذكي", category:"المفاتيح", tag:"تعتيم الإضاءة", kind:"switch", image:"/__mockup/images/noura-smart-dme213.png", specs:["Zigbee 3.0","رفع وخفض شدة الإضاءة","زر تشغيل وإيقاف","ألوان متعددة"], note:"اضبط إضاءة المكان على مزاجك، واختر اللون المناسب لمساحتك.", accent:"coral", colors:[{name:"أسود",hex:"#202020"},{name:"ذهبي",hex:"#b48743"},{name:"أبيض",hex:"#f4f1ec"},{name:"رمادي",hex:"#8d8d8d"}] },
  { id:12, name:"سويتش ستارة ذكي", category:"المفاتيح", tag:"تحكم بالستارة", kind:"switch", image:"/__mockup/images/noura-smart-dme291.png", specs:["Zigbee 3.0","زر فتح وإغلاق وإيقاف","إطار معدني أسود","تحكم عبر التطبيق"], note:"تحكم ناعم بالضوء والخصوصية من نفس مكانه.", accent:"slate", colors:[{name:"أسود",hex:"#202020"},{name:"ذهبي",hex:"#b48743"},{name:"أبيض",hex:"#f4f1ec"},{name:"رمادي",hex:"#8d8d8d"}] },
  { id:17, name:"حساس مستوى خزان الماء", category:"الحساسات", tag:"خزان الماء", kind:"sensor", image:"/__mockup/images/noura-smart-new-water-tank.jpg", specs:["حساس مستوى","تصميم برتقالي واضح","سلك استشعار طويل","تنبيه عند تغير المستوى"], note:"يراقب مستوى الماء في الخزان ويعطيك تنبيهاً قبل المفاجآت.", accent:"gold" },
  { id:18, name:"حساس اهتزاز ذكي", category:"الحساسات", tag:"اهتزاز", kind:"sensor", image:"/__mockup/images/noura-smart-vibration.jpg", specs:["كشف الاهتزاز","تنبيه فوري","اتصال لاسلكي","تصميم مدمج"], note:"يراقب الأبواب والخزائن والأجهزة الحساسة للحركة.", accent:"slate" },
  { id:19, name:"حساس حركة للزاوية", category:"الحساسات", tag:"زاوية واسعة", kind:"sensor", image:"/__mockup/images/noura-smart-new-motion-angle.jpg", specs:["كشف حركة للزاوية","تغطية واسعة","تنبيه ذكي","تركيب جداري"], note:"حساس مخصص للزوايا والممرات لمراقبة الحركة من نقطة أوسع.", accent:"teal" },
  { id:20, name:"حساس تسريب ماء — شريطي", category:"الحساسات", tag:"تسريب الماء", kind:"sensor", image:"/__mockup/images/noura-smart-new-leak-long.jpg", specs:["مسبار تسريب طويل","تنبيه فوري","تصميم أبيض","للمطابخ ودورات المياه"], note:"يرصد بداية التسريب في الأماكن الضيقة وحول الأنابيب.", accent:"slate" },
  { id:21, name:"حساس تسريب ماء — دائري", category:"الحساسات", tag:"تسريب الماء", kind:"sensor", image:"/__mockup/images/noura-smart-new-leak-round.jpg", specs:["حساس قطرة ماء","سطح دائري","تنبيه فوري","تركيب سهل"], note:"حساس دائري صغير يوضع قرب مصادر الماء.", accent:"teal" },
  { id:22, name:"حساس رطوبة التربة", category:"الحساسات", tag:"للنباتات", kind:"sensor", image:"/__mockup/images/noura-smart-new-soil.jpg", specs:["قياس رطوبة التربة","مسبار طويل","تنبيه للسقي","للنباتات الداخلية"], note:"يساعدك تعرف متى تحتاج النبتة إلى الماء بدون تخمين.", accent:"gold" },
  { id:23, name:"مقوي إشارة USB", category:"الملحقات", tag:"تقوية الإشارة", kind:"accessory", image:"/__mockup/images/noura-smart-new-usb.jpg", specs:["USB","توسيع نطاق الشبكة","زر اقتران","تصميم صغير"], note:"يقوي تغطية الإشارة للأجهزة البعيدة داخل المنزل.", accent:"slate" },
  { id:24, name:"حساس الشروق والغروب", category:"الحساسات", tag:"إضاءة طبيعية", kind:"sensor", image:"/__mockup/images/noura-smart-new-sunrise.jpg", specs:["حساس ضوء","تفعيل المشاهد تلقائياً","تصميم مربع أسود","للاستخدام الخارجي"], note:"يشغل مشاهد البيت مع تغير ضوء النهار.", accent:"slate" },
  { id:25, name:"حساس IR للتحكم", category:"الملحقات", tag:"TV والمكيف", kind:"accessory", image:"/__mockup/images/noura-smart-new-ir.jpg", specs:["تحكم IR","للتلفزيون والمكيف","مشاهد مخصصة","تصميم أسود دائري"], note:"يجمع أجهزة التحكم بالأشعة تحت الحمراء في مشهد واحد.", accent:"coral" },
  { id:26, name:"حساس حنفية الهوز", category:"الحساسات", tag:"للخارج", kind:"sensor", image:"/__mockup/images/noura-smart-new-faucet.jpg", specs:["للحنفية الخارجية","تحكم بالهوز","تنبيه ذكي","تصميم أخضر"], note:"حل ذكي لحنفية الهوز الخارجية والتحكم بالماء.", accent:"teal" },
];

const categoryMeta:Record<Category,{icon:typeof Home; label:string}> = {
  الكل:{icon:Home,label:"كل المنتجات"}, الشاشات:{icon:Radio,label:"الشاشات"}, المفاتيح:{icon:Zap,label:"المفاتيح"}, الحساسات:{icon:ShieldCheck,label:"الحساسات"}, الملحقات:{icon:Cpu,label:"الملحقات"}
};

function ProductVisual({product}:{product:Product}) {
  return <div className={`noura-visual noura-${product.kind}`}>
    <div className="noura-visual-grid" />
    <img className="noura-product-photo" src={product.image} alt={product.name} />
    <span className="noura-visual-code">NOURA / {String(product.id).padStart(2,"0")}</span>
  </div>;
}

function ProductCard({product,onOpen,expanded,onToggle}:{product:Product;onOpen:(p:Product)=>void;expanded:boolean;onToggle:()=>void}) {
  return <article className={`noura-card noura-rise tone-${product.accent} ${expanded?"is-expanded":""} ${product.kind==="switch"?"is-switch":""}`} onClick={product.kind==="switch"?onToggle:undefined}>
    <div className="noura-card-art"><span className="noura-tag">{product.tag}</span><button className="noura-more" aria-label="عرض التفاصيل" onClick={e=>{e.stopPropagation();onOpen(product)}}><ArrowLeft size={17}/></button><ProductVisual product={product}/></div>
    <div className="noura-card-body"><div className="noura-card-kicker">{product.category}<span>•</span><span className="noura-mono">NOURA {String(product.id).padStart(2,"0")}</span></div><h3>{product.name}</h3><p>{product.note}</p><div className="noura-specs">{product.specs.slice(0,3).map(s=><span key={s}>{s}</span>)}</div>{product.kind==="switch"&&product.colors&&<div className="noura-switch-colors" onClick={e=>e.stopPropagation()}><div className="noura-switch-colors-head"><span>الألوان المتوفرة</span><span className="noura-switch-colors-hint">{expanded?"إخفاء":"اضغط لعرض الألوان"}</span></div>{expanded&&<div className="noura-color-options">{product.colors.map(color=><span className="noura-color-option" key={color.name}><i style={{backgroundColor:color.hex}}/><b>{color.name}</b></span>)}</div>}</div>}<div className="noura-card-foot"><span className="noura-spec-label">{product.kind==="switch"?"اضغط على البطاقة للألوان":"المواصفات والتفاصيل"}</span><button onClick={e=>{e.stopPropagation();onOpen(product)}} className="noura-detail">عرض التفاصيل <ArrowLeft size={15}/></button></div></div>
  </article>;
}

export function NouraSmartStore() {
  const [category,setCategory] = useState<Category>("الكل");
  const [search,setSearch] = useState("");
  const [selected,setSelected] = useState<Product|null>(null);
  const [expandedSwitch,setExpandedSwitch] = useState<number|null>(null);
  const [menu,setMenu] = useState(false);
  const filtered = useMemo(()=>products.filter(p=>(category==="الكل"||p.category===category)&&p.name.includes(search)),[category,search]);
  return <main dir="rtl" className="noura-store noura-noise min-h-screen">
     <header className="noura-header"><div className="noura-wrap noura-nav"><button className="noura-mobile-menu" onClick={()=>setMenu(!menu)} aria-label="القائمة">{menu?<X/>:<Menu/>}</button><a className="noura-logo" href="#top"><img src="/__mockup/images/noura-smart-logo.png" alt="نورة" /><span><b>نورة سمارت</b><small>SMART HOME</small></span></a><nav className={menu?"is-open":""}>{["المنتجات","لماذا نورة","الدعم"].map((item,i)=><a key={item} href={i===0?"#products":"#promise"} onClick={()=>setMenu(false)}>{item}</a>)}</nav><div className="noura-nav-actions"><label className="noura-search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ابحث عن منتج" aria-label="بحث"/></label><button className="noura-icon-btn" aria-label="الملف الشخصي"><span>ن</span></button></div></div></header>
    <section id="top" className="noura-hero noura-wrap"><div className="noura-hero-copy noura-rise"><div className="noura-eyebrow"><span /> بيتك، بإيقاعك</div><h1>تقنية تفهم<br/><em>هدوء البيت.</em></h1><p>أجهزة ذكية مختارة بعناية، لتجعل تفاصيل يومك أسهل — وتبقى أنت في الصورة.</p><a className="noura-hero-cta" href="#products">استكشف المنتجات <ArrowLeft size={18}/></a></div><div className="noura-hero-orb"><div className="noura-orb-inner"><div className="noura-orb-house"><Home size={46}/></div><span className="orb-label orb-one">اتصال أسهل</span><span className="orb-label orb-two">حياة أهدأ</span><span className="orb-label orb-three">اختيار أذكى</span></div><div className="noura-orbit orbit-a"/><div className="noura-orbit orbit-b"/></div><div className="noura-hero-aside"><span className="noura-mono">01 / 03</span><span className="noura-vertical">SMART LIVING / RIYADH</span></div></section>
    <section className="noura-strip"><div className="noura-wrap noura-strip-inner"><span><ShieldCheck size={18}/> ضمان نورة المحلي</span><span><Radio size={18}/> منتجات متوافقة</span><span><Cpu size={18}/> مواصفات واضحة</span><span><Zap size={18}/> إعداد بلا تعقيد</span></div></section>
     <section id="products" className="noura-products noura-wrap"><div className="noura-section-head"><div><div className="noura-eyebrow"><span /> اختيارات للبيت المتصل</div><h2>الأجهزة التي <em>تستحق مكانها.</em></h2></div><p>كل منتج هنا له وظيفة واضحة، ومواصفات نكتبها كما هي.</p></div><div className="noura-filter-row"><div className="noura-categories">{(Object.keys(categoryMeta) as Category[]).map(c=>{const Icon=categoryMeta[c].icon;return <button key={c} className={category===c?"active":""} onClick={()=>setCategory(c)}><Icon size={16}/>{categoryMeta[c].label}<span className="noura-count">{c==="الكل"?products.length:products.filter(p=>p.category===c).length}</span></button>})}</div><button className="noura-filter"><SlidersHorizontal size={16}/> ترتيب: المميز <ChevronDown size={15}/></button></div>{filtered.length?<div className="noura-grid">{filtered.map(p=><ProductCard key={p.id} product={p} expanded={expandedSwitch===p.id} onToggle={()=>setExpandedSwitch(expandedSwitch===p.id?null:p.id)} onOpen={setSelected}/>)}</div>:<div className="noura-empty"><Filter size={28}/><h3>لم نجد هذا المنتج بعد</h3><p>جرّب كلمة أقصر أو استعرض كل المنتجات.</p><button onClick={()=>{setSearch("");setCategory("الكل")}}>عرض كل المنتجات</button></div>}</section>
    <section id="promise" className="noura-promise"><div className="noura-wrap noura-promise-grid"><div><div className="noura-eyebrow"><span /> فلسفة نورة</div><h2>البيت الذكي<br/><em>لا يحتاج أن يصرخ.</em></h2></div><div className="noura-promise-copy"><p>نختار التقنية التي تندمج مع يومك، لا التي تطلب منك تغيير طريقتك. أجهزة موثوقة، معلومات صريحة، ولمسة سعودية تعرف معنى البيت.</p><span className="noura-mono">N / 2024 — 1446</span></div><div className="noura-promise-stamp">مصمم<br/>للبيت<br/><b>السعودي</b></div></div></section>
     <footer className="noura-footer"><div className="noura-wrap"><div className="noura-footer-top"><a className="noura-logo" href="#top"><img src="/__mockup/images/noura-smart-logo.png" alt="نورة" /><span><b>نورة سمارت</b><small>SMART HOME</small></span></a><p>تقنية أقرب. بيت أهدأ.</p><a href="#top" className="noura-back">العودة للأعلى <ChevronUp size={17}/></a></div><div className="noura-footer-bottom"><span>© نورة سمارت — الرياض، المملكة العربية السعودية</span><span>المتجر التعريفي · المواصفات أولاً</span></div></div></footer>
     {selected&&<div className="noura-modal-backdrop" onClick={()=>setSelected(null)}><section className="noura-modal" onClick={e=>e.stopPropagation()}><button className="noura-modal-close" onClick={()=>setSelected(null)} aria-label="إغلاق"><X/></button><ProductVisual product={selected}/><div className="noura-modal-content"><div className="noura-card-kicker">{selected.category} <span>•</span> <span className="noura-mono">NOURA {String(selected.id).padStart(2,"0")}</span></div><h2>{selected.name}</h2><p>{selected.note}</p><div className="noura-modal-price">المواصفات التقنية</div><div className="noura-detail-list">{selected.specs.map((s,i)=><div key={s}><span className="noura-mono">0{i+1}</span><b>{s}</b></div>)}</div><div className="noura-modal-note">هذا المنتج جزء من كتالوج نورة سمارت التعريفي. للمزيد من المعلومات، تواصل مع فريقنا.</div></div></section></div>}
  </main>;
}